const tarotDeck = [
    { number: 0, name: 'The Fool', icon: '🃏', image: 'asset/tarot/00_Fool.jpg', meaning: `The Fool represents the beginning of a spiritual journey, embodying innocence, spontaneity, and a free spirit. This card signifies new beginnings, fresh starts, and the courage to step into the unknown without fear. It encourages you to trust in the universe and take a leap of faith, even when the path ahead is unclear. The Fool reminds you to embrace your inner child, be open to new experiences, and approach life with optimism and wonder. This is a time for adventure, exploration, and following your heart's desires without overthinking or being constrained by societal expectations. The Fool asks you to trust your instincts and believe that the universe will support you on your journey.`, reverse: `When reversed, The Fool warns against recklessness, impulsive decisions, and foolish behavior. You may be taking unnecessary risks without proper planning or consideration of consequences. This card suggests fear of the unknown is holding you back from taking necessary steps forward. You might be living in denial, avoiding responsibility, or refusing to grow up and face reality. The reversed Fool can indicate naivety, gullibility, or being taken advantage of due to lack of experience or wisdom. It's time to be more cautious, think before you act, and develop better judgment in your decisions.` },
    { number: 1, name: 'The Magician', icon: '✨', image: 'asset/tarot/01_Magician.jpg', meaning: `The Magician is a powerful card of manifestation, representing your ability to turn dreams into reality through focused will and action. This card signifies that you have all the tools, skills, and resources you need to achieve your goals - you just need to harness them effectively. The Magician embodies confidence, creativity, and the power of intention. It's a reminder that you are the creator of your own reality and that through concentration, determination, and proper use of your talents, you can manifest your desires. This card often appears when you're entering a period of inspired action, where your thoughts, words, and deeds align perfectly to bring about positive change. The Magician encourages you to tap into your full potential and use your unique gifts to make magic happen in your life.`, reverse: `Reversed, The Magician warns of manipulation, deception, and misuse of power. You may be using your skills and talents for selfish purposes or to manipulate others. This card can indicate poor planning, lack of focus, or scattered energy that prevents you from achieving your goals. You might have untapped potential that you're not utilizing, or you're doubting your abilities and not believing in yourself. The reversed Magician can also suggest trickery, con artists, or someone trying to deceive you. It's important to examine your intentions and ensure you're using your power ethically and for the highest good of all involved.` },
    { number: 2, name: 'The High Priestess', icon: '🌙', image: 'asset/tarot/02_High_Priestess.jpg', meaning: `The High Priestess is the guardian of the subconscious mind and the keeper of sacred knowledge. She represents intuition, inner wisdom, and the divine feminine energy within all of us. This card encourages you to trust your inner voice and pay attention to your dreams, instincts, and gut feelings. The High Priestess sits at the threshold between the conscious and unconscious realms, reminding you that not everything needs to be understood intellectually - some truths can only be felt and experienced. She invites you to explore your spirituality, develop your psychic abilities, and connect with your higher self. This is a time for introspection, meditation, and listening to the whispers of your soul. The High Priestess teaches that true wisdom comes from within and that by going inward, you'll find the answers you seek.`, reverse: `When reversed, The High Priestess indicates disconnection from your intuition and inner wisdom. You may be ignoring your gut feelings or dismissing your instincts in favor of logic and rational thinking. This card can suggest secrets being kept from you, hidden agendas, or information being withheld. You might be experiencing confusion, lack of clarity, or difficulty accessing your subconscious mind. The reversed High Priestess can also indicate superficiality, focusing too much on external appearances rather than inner truth. It's time to reconnect with your intuitive self, pay attention to your dreams and inner guidance, and trust that you have access to profound wisdom if you're willing to listen.` },
    { number: 3, name: 'The Empress', icon: '👑', image: 'asset/tarot/03_Empress.jpg', meaning: `The Empress embodies the divine feminine in her fullest expression - nurturing, abundant, creative, and deeply connected to nature. She represents fertility in all forms: physical pregnancy, creative projects, or the birth of new ideas. This card signifies a time of growth, abundance, and prosperity in your life. The Empress encourages you to connect with your senses, appreciate beauty, and indulge in life's pleasures. She reminds you to nurture yourself and others, creating a loving and supportive environment. This is a period of creativity and artistic expression, where your ideas flow freely and manifest into tangible results. The Empress also represents mother energy - whether you're a mother yourself or need mothering from others. She teaches the importance of self-care, compassion, and creating harmony in your surroundings.`, reverse: `Reversed, The Empress can indicate creative blocks, lack of growth, or difficulty nurturing yourself or others. You may be experiencing dependence on others for validation or support, or conversely, you might be smothering others with excessive care. This card can suggest neglecting your own needs, ignoring your body's signals, or disconnecting from nature and beauty. Financial difficulties or lack of abundance may be present. The reversed Empress can also indicate issues with fertility, pregnancy complications, or challenges in creative projects. It's time to reconnect with your creative source, practice better self-care, and find balance between giving and receiving.` },
    { number: 4, name: 'The Emperor', icon: '⚔️', image: 'asset/tarot/04_Emperor.jpg', meaning: `The Emperor represents authority, structure, and the establishment of order. He embodies the divine masculine energy - strong, protective, and disciplined. This card signifies leadership, taking control of your life, and establishing clear boundaries and rules. The Emperor encourages you to be strategic, organized, and methodical in your approach to challenges. He represents father energy, providing structure, guidance, and protection. This is a time to take charge, assert your authority, and create stability in your life. The Emperor teaches the importance of discipline, responsibility, and following through on commitments. He reminds you that true power comes from self-control and the ability to create order from chaos. This card often appears when you need to be more assertive, set clear goals, and take decisive action.`, reverse: `When reversed, The Emperor warns of domination, excessive control, and abuse of power. You may be experiencing tyrannical behavior from authority figures or exhibiting controlling tendencies yourself. This card can indicate lack of discipline, inability to follow through on plans, or resistance to structure and rules. You might be avoiding responsibility or refusing to take charge when leadership is needed. The reversed Emperor can suggest father issues, problems with authority figures, or difficulty establishing healthy boundaries. Rigidity, inflexibility, and unwillingness to adapt can also be indicated. It's time to examine your relationship with power and authority, finding balance between control and flexibility.` },
    { number: 5, name: 'The Hierophant', icon: '🏛️', image: 'asset/tarot/05_Hierophant.jpg', meaning: `The Hierophant represents spiritual wisdom, traditional values, and established institutions. He is the bridge between the divine and the earthly, teaching sacred knowledge and guiding others on their spiritual path. This card signifies conformity to social norms, following established rules and traditions, and seeking guidance from mentors or spiritual teachers. The Hierophant encourages you to honor tradition, respect cultural heritage, and learn from those who came before you. He represents formal education, religious institutions, and organized belief systems. This is a time to seek counsel from wise elders, join groups or communities that share your values, and participate in rituals or ceremonies. The Hierophant teaches that there is wisdom in tradition and that sometimes following established paths can lead to spiritual growth and understanding.`, reverse: `Reversed, The Hierophant indicates rebellion against tradition, challenging the status quo, and questioning established beliefs. You may be breaking free from restrictive religious or cultural conditioning, choosing to forge your own spiritual path. This card can suggest feeling constrained by rules and regulations, or experiencing conflict with authority figures or institutions. You might be developing your own personal belief system rather than accepting what you've been taught. The reversed Hierophant can also indicate unconventional relationships, alternative lifestyles, or rejection of societal expectations. It's time to think for yourself, question everything, and discover what truly resonates with your soul rather than blindly following tradition.` },
    { number: 6, name: 'The Lovers', icon: '💞', image: 'asset/tarot/06_Lovers.jpg', meaning: `The Lovers card represents deep connections, harmony, and the power of choice. While often associated with romantic relationships, this card speaks to all forms of union - partnerships, collaborations, and the integration of opposites within yourself. The Lovers signify a time of important decisions, particularly those involving relationships and values. This card encourages you to align your actions with your core beliefs and choose paths that honor your authentic self. It represents the harmony that comes from accepting and integrating all parts of yourself - the light and shadow, masculine and feminine, conscious and unconscious. The Lovers teach that true union requires vulnerability, trust, and the courage to be fully seen. This is a time for heart-centered decisions, deep connections, and choosing love over fear.`, reverse: `Reversed, The Lovers indicate disharmony in relationships, misalignment of values, or difficulty making important decisions. You may be experiencing conflict between your heart and mind, or struggling with self-love and self-acceptance. This card can suggest imbalanced relationships, codependency, or choosing partners who don't align with your values. You might be avoiding important decisions or making choices based on fear rather than love. The reversed Lovers can also indicate inner conflict, lack of self-acceptance, or difficulty integrating different aspects of your personality. It's time to examine your relationships, clarify your values, and make choices that honor your true self.` },
    { number: 7, name: 'The Chariot', icon: '🛡️', image: 'asset/tarot/07_Chariot.jpg', meaning: `The Chariot represents victory, determination, and the power of focused will. This card signifies overcoming obstacles through discipline, confidence, and unwavering commitment to your goals. The Chariot teaches that success comes from harnessing opposing forces and directing them toward a common purpose. Like a skilled charioteer controlling two horses, you must balance different aspects of yourself - emotion and logic, action and patience, ambition and compassion. This is a time of forward movement, achievement, and triumph over adversity. The Chariot encourages you to take control of your life, assert your will, and move confidently toward your destination. Success is within reach, but it requires focus, determination, and the ability to stay on course despite distractions or challenges.`, reverse: `When reversed, The Chariot warns of lack of direction, loss of control, or being pulled in too many directions at once. You may be experiencing opposition, setbacks, or difficulty maintaining focus on your goals. This card can indicate aggression, forcing outcomes, or trying to control situations that require a gentler approach. You might be lacking self-discipline, giving up too easily, or allowing obstacles to derail your progress. The reversed Chariot can also suggest internal conflict, where different parts of yourself are working against each other rather than in harmony. It's time to reassess your goals, regain your focus, and develop better strategies for moving forward.` },
    { number: 8, name: 'Strength', icon: '🦁', image: 'asset/tarot/08_Strength.jpg', meaning: `Strength represents inner fortitude, courage, and the power of gentle persuasion over brute force. This card teaches that true strength comes from compassion, patience, and the ability to tame your inner beasts through love rather than violence. Strength signifies mastery over your instincts, emotions, and base desires through higher consciousness and self-control. This is not about suppressing your wild nature, but about integrating it with wisdom and grace. The Strength card encourages you to face challenges with courage and confidence, knowing that you have the inner resources to overcome any obstacle. It represents resilience, determination, and the quiet power that comes from self-assurance. This is a time to be brave, trust in your abilities, and approach difficulties with compassion and understanding rather than force or aggression.`, reverse: `Reversed, Strength indicates self-doubt, lack of confidence, or feeling overwhelmed by your emotions and instincts. You may be experiencing weakness, vulnerability, or inability to control your impulses. This card can suggest raw emotion taking over, acting out of fear or anger, or allowing your shadow side to dominate. You might be being too hard on yourself, lacking self-compassion, or feeling defeated by challenges. The reversed Strength can also indicate abuse of power, using force when gentleness is needed, or bullying behavior. It's time to reconnect with your inner strength, practice self-compassion, and remember that true power comes from love, not fear.` },
    { number: 9, name: 'The Hermit', icon: '🏮', image: 'asset/tarot/09_Hermit.jpg', meaning: `The Hermit represents introspection, solitude, and the search for inner truth. This card signifies a time of withdrawal from the external world to focus on your inner journey. The Hermit teaches that wisdom comes from within and that sometimes you must step away from the noise and distractions of daily life to hear your soul's voice. This is a period of soul-searching, meditation, and deep contemplation. The Hermit encourages you to seek guidance from your inner teacher, trust your own wisdom, and find answers within yourself rather than looking to others. This card often appears when you need time alone to process experiences, heal, or gain clarity about your life's direction. The Hermit reminds you that solitude is not loneliness - it's a sacred space for self-discovery and spiritual growth.`, reverse: `When reversed, The Hermit warns of isolation, loneliness, or withdrawing too much from the world. You may be avoiding social interaction, refusing help from others, or becoming a recluse. This card can indicate feeling lost, lacking direction, or being unable to find the answers you seek despite introspection. You might be rejecting wise counsel, refusing to learn from experience, or stubbornly insisting on doing everything alone. The reversed Hermit can also suggest fear of solitude, inability to be alone with yourself, or constantly seeking external validation. It's time to find balance between solitude and connection, between inner work and outer engagement with the world.` },
    { number: 10, name: 'Wheel of Fortune', icon: '🎡', image: 'asset/tarot/10_Wheel_of_Fortune.jpg', meaning: `The Wheel of Fortune represents the cycles of life, destiny, and the ever-turning nature of existence. This card signifies that change is inevitable and that life moves in cycles of ups and downs, beginnings and endings. The Wheel teaches that nothing is permanent - good times will pass, but so will difficult times. This is a card of karma, suggesting that what goes around comes around and that your past actions are now bearing fruit. The Wheel of Fortune often indicates a turning point, a stroke of luck, or a significant shift in circumstances. It encourages you to embrace change, trust in the natural flow of life, and understand that you're part of a larger cosmic pattern. This card reminds you that while you can't control everything, you can control how you respond to life's changes.`, reverse: `Reversed, The Wheel of Fortune indicates bad luck, resistance to change, or feeling stuck in negative cycles. You may be experiencing setbacks, disappointments, or a downturn in circumstances. This card can suggest that you're fighting against inevitable changes or trying to hold onto situations that need to end. You might be repeating negative patterns, unable to break free from destructive cycles, or feeling like a victim of fate. The reversed Wheel can also indicate that you're not learning from past experiences or that karma is catching up with you in challenging ways. It's time to accept that change is necessary, release what no longer serves you, and trust that the wheel will turn again in your favor.` },
    { number: 11, name: 'Justice', icon: '⚖️', image: 'asset/tarot/11_Justice.jpg', meaning: `Justice represents fairness, truth, and the law of cause and effect. This card signifies that actions have consequences and that balance must be restored. Justice teaches that you reap what you sow and that the universe operates according to natural laws of equilibrium. This is a time for honesty, integrity, and taking responsibility for your actions. The Justice card encourages you to make fair and balanced decisions, consider all perspectives, and act with integrity. It often appears in situations involving legal matters, contracts, or important decisions that require careful consideration. Justice reminds you that truth will prevail and that fairness will ultimately be served. This card asks you to examine your conscience, make amends where necessary, and ensure that your actions align with your values and principles.`, reverse: `When reversed, Justice warns of unfairness, dishonesty, or lack of accountability. You may be experiencing injustice, bias, or situations where the truth is being distorted. This card can indicate avoiding responsibility, refusing to face consequences, or making decisions based on prejudice rather than facts. You might be being treated unfairly or treating others unjustly. The reversed Justice can also suggest legal troubles, contracts falling through, or decisions being made without proper consideration. It's time to examine your integrity, take responsibility for your actions, and work toward restoring balance and fairness in your life and relationships.` }
];

const tarotDeck2 = [
    { number: 12, name: 'The Hanged Man', icon: '🧘', image: 'asset/tarot/12_Hanged_Man.jpg', meaning: `The Hanged Man represents surrender, letting go, and seeing things from a new perspective. This card signifies a period of suspension, where you must pause, release control, and allow life to unfold naturally. The Hanged Man teaches that sometimes the best action is inaction, and that by surrendering to the present moment, you gain profound insights. This is a time of sacrifice, where you may need to give up something to gain something greater. The Hanged Man encourages you to look at situations from a different angle, challenge your assumptions, and embrace the wisdom that comes from stillness. This card often appears when you're being asked to let go of old patterns, release attachments, and trust in divine timing. The Hanged Man reminds you that sometimes you must lose yourself to find yourself.`, reverse: `Reversed, The Hanged Man indicates resistance to necessary change, unwillingness to let go, or feeling stuck in limbo. You may be experiencing delays, stalling, or inability to move forward because you're clinging to old ways. This card can suggest martyrdom, playing the victim, or making unnecessary sacrifices. You might be resisting new perspectives, refusing to see things differently, or stubbornly holding onto control when surrender is needed. The reversed Hanged Man can also indicate indecision, procrastination, or fear of making necessary changes. It's time to release what's holding you back, embrace new perspectives, and trust that letting go will lead to growth.` },
    { number: 13, name: 'Death', icon: '💀', image: 'asset/tarot/13_Death.jpg', meaning: `Death represents transformation, endings, and the natural cycle of life. Despite its ominous appearance, this card rarely predicts physical death. Instead, it signifies profound change, the ending of one chapter and the beginning of another. Death teaches that transformation is necessary for growth and that sometimes things must end to make room for new beginnings. This is a time of letting go, releasing the old, and embracing the new. The Death card encourages you to accept change, even when it's difficult or painful, knowing that it's clearing the way for something better. This card often appears during major life transitions - career changes, relationship endings, moving to new places, or fundamental shifts in identity. Death reminds you that endings are not failures but natural parts of life's journey, and that through death comes rebirth.`, reverse: `When reversed, Death indicates resistance to change, fear of endings, or inability to let go of the past. You may be clinging to situations, relationships, or identities that no longer serve you. This card can suggest stagnation, refusing to move forward, or being stuck in transition. You might be experiencing personal transformation that's happening internally rather than externally, or you're going through a period of inner purging and release. The reversed Death can also indicate fear of change, avoiding necessary endings, or trying to resurrect what should remain in the past. It's time to accept that change is inevitable, release your grip on what's ending, and trust that transformation will lead to renewal.` },
    { number: 14, name: 'Temperance', icon: '🏺', image: 'asset/tarot/14_Temperance.jpg', meaning: `Temperance represents balance, moderation, and the art of blending opposites into harmony. This card signifies patience, purpose, and the middle path between extremes. Temperance teaches that true power comes from finding equilibrium and that healing occurs through integration rather than elimination. This is a time for patience, taking things slowly, and allowing natural processes to unfold. The Temperance card encourages you to blend different aspects of your life, find compromise in conflicts, and create harmony from discord. It represents the alchemical process of transformation, where opposing elements are combined to create something new and beautiful. Temperance reminds you to practice moderation, avoid extremes, and trust in divine timing. This card often appears when you need to be patient, practice self-control, and work toward long-term goals with steady, consistent effort.`, reverse: `Reversed, Temperance warns of imbalance, excess, or lack of moderation. You may be experiencing extremes in behavior, emotions, or lifestyle choices. This card can indicate impatience, rushing processes that need time, or forcing outcomes rather than allowing natural flow. You might be struggling with addiction, overindulgence, or inability to find middle ground. The reversed Temperance can also suggest lack of harmony, conflicting interests, or difficulty integrating different aspects of your life. It's time to restore balance, practice moderation, and realign with your higher purpose and values.` },
    { number: 15, name: 'The Devil', icon: '⛓️', image: 'asset/tarot/15_Devil.jpg', meaning: `The Devil represents bondage, materialism, and the shadow aspects of human nature. This card signifies attachments, addictions, and the ways we enslave ourselves through fear, desire, and limiting beliefs. The Devil teaches that we often create our own prisons through unhealthy patterns, toxic relationships, or obsessive behaviors. This is a time to examine what controls you - whether it's substances, people, beliefs, or material possessions. The Devil card encourages you to confront your shadow self, acknowledge your darker impulses, and recognize where you've given away your power. It represents sexuality, primal instincts, and the physical realm. The Devil reminds you that while these chains may feel real, they're often self-imposed, and you have the power to break free at any time. This card asks you to take responsibility for your choices and reclaim your freedom.`, reverse: `When reversed, The Devil indicates breaking free from bondage, releasing limiting beliefs, or overcoming addictions. You may be recognizing unhealthy patterns and taking steps to change them. This card can suggest exploring your shadow side, confronting your fears, or releasing attachments that have held you back. You might be detaching from toxic relationships, breaking bad habits, or liberating yourself from self-imposed restrictions. The reversed Devil can also indicate that you're ready to face your demons, acknowledge your darkness, and integrate your shadow aspects. It's time to reclaim your power, break free from what binds you, and step into greater freedom and authenticity.` },
    { number: 16, name: 'The Tower', icon: '⚡', image: 'asset/tarot/16_Tower.jpg', meaning: `The Tower represents sudden change, upheaval, and the destruction of false structures. This card signifies a dramatic shift that shakes the very foundation of your life, forcing you to rebuild from the ground up. The Tower teaches that sometimes things must fall apart so they can come together in a better way. This is a time of revelation, awakening, and the shattering of illusions. The Tower card often appears during crisis, chaos, or unexpected events that disrupt your sense of security. While this can be frightening and painful, The Tower ultimately serves a higher purpose - clearing away what's false, outdated, or built on shaky ground. This card encourages you to embrace the chaos, trust in the process of destruction and renewal, and understand that what's falling away needed to go. The Tower reminds you that true security comes from within, not from external structures.`, reverse: `Reversed, The Tower indicates fear of change, averting disaster, or experiencing personal transformation rather than external upheaval. You may be resisting necessary changes, trying to hold onto crumbling structures, or avoiding the inevitable. This card can suggest that you're going through internal crisis rather than external chaos, or that you're having a spiritual awakening that's dismantling your old belief systems. You might be narrowly avoiding disaster or experiencing smaller disruptions that serve as warnings. The reversed Tower can also indicate that you're clinging to false security or refusing to see the truth about situations that need to change. It's time to accept that transformation is necessary and that sometimes destruction is the path to liberation.` },
    { number: 17, name: 'The Star', icon: '⭐', image: 'asset/tarot/17_Star.jpg', meaning: `The Star represents hope, faith, and spiritual renewal. This card signifies a time of healing, inspiration, and connection to something greater than yourself. The Star teaches that even in the darkest night, there is light to guide you. This is a period of optimism, serenity, and trust in the universe. The Star card encourages you to have faith in the future, believe in yourself, and trust that you're being guided toward your highest good. It represents clarity of purpose, spiritual insight, and the feeling of being aligned with your true path. The Star often appears after difficult times, offering hope and reassurance that better days are ahead. This card reminds you to stay positive, maintain your faith, and trust in divine timing. The Star teaches that you are a channel for cosmic energy and that by staying open and receptive, you can manifest your dreams.`, reverse: `When reversed, The Star indicates lack of faith, despair, or feeling disconnected from hope and inspiration. You may be experiencing doubt, pessimism, or inability to see the light at the end of the tunnel. This card can suggest loss of faith in yourself or the universe, feeling abandoned, or struggling to find meaning and purpose. You might be disconnected from your spirituality, lacking inspiration, or unable to trust in positive outcomes. The reversed Star can also indicate self-doubt, low self-esteem, or feeling unworthy of blessings. It's time to reconnect with hope, restore your faith, and remember that you are worthy of all the good things life has to offer.` },
    { number: 18, name: 'The Moon', icon: '🐺', image: 'asset/tarot/18_Moon.jpg', meaning: `The Moon represents illusion, intuition, and the mysterious realm of the subconscious. This card signifies a time of uncertainty, where things are not as they seem and truth is obscured by shadows. The Moon teaches that not everything can be understood through logic and reason - some truths can only be felt and intuited. This is a period of heightened sensitivity, vivid dreams, and deep emotional currents. The Moon card encourages you to trust your intuition, pay attention to your dreams, and navigate by inner knowing rather than external facts. It represents fears, anxieties, and the shadow aspects of the psyche that emerge in darkness. The Moon often appears when you're dealing with deception, confusion, or situations where clarity is lacking. This card reminds you to be patient, trust your instincts, and understand that the full truth will be revealed in time.`, reverse: `Reversed, The Moon indicates release of fear, clarity emerging from confusion, or confronting repressed emotions. You may be seeing through illusions, uncovering deception, or gaining insight into previously mysterious situations. This card can suggest that fears are subsiding, anxiety is lessening, or you're finding your way out of confusion. You might be releasing repressed emotions, confronting your shadow self, or bringing unconscious patterns into conscious awareness. The reversed Moon can also indicate inner confusion, self-deception, or being overwhelmed by emotions. It's time to face your fears, trust your intuition, and bring light to the shadows.` },
    { number: 19, name: 'The Sun', icon: '☀️', image: 'asset/tarot/19_Sun.jpg', meaning: `The Sun represents joy, success, and the radiant energy of life itself. This card signifies a time of celebration, achievement, and basking in the warmth of positive outcomes. The Sun teaches that after darkness comes light, and that life is meant to be enjoyed. This is a period of vitality, confidence, and feeling fully alive. The Sun card encourages you to embrace your authentic self, shine your light brightly, and share your gifts with the world. It represents clarity, truth, and the illumination of all that was hidden. The Sun often appears when you're experiencing success, recognition, or a sense of accomplishment. This card reminds you to be optimistic, maintain a positive attitude, and trust that everything is working out for your highest good. The Sun teaches that you are a radiant being of light and that by embracing your true nature, you inspire others to do the same.`, reverse: `When reversed, The Sun indicates temporary setbacks, dampened enthusiasm, or difficulty seeing the positive side of situations. You may be experiencing delays in success, feeling less confident, or struggling to maintain optimism. This card can suggest that you're being overly optimistic, ignoring problems, or wearing rose-colored glasses. You might be experiencing inner sadness despite outer success, or feeling disconnected from your inner child and sense of joy. The reversed Sun can also indicate that success is coming but taking longer than expected. It's time to reconnect with your inner light, find reasons to be grateful, and trust that the sun will shine again.` },
    { number: 20, name: 'Judgement', icon: '🎺', image: 'asset/tarot/20_Judgement.jpg', meaning: `Judgement represents awakening, rebirth, and answering a higher calling. This card signifies a time of reckoning, where you're called to account for your actions and make important decisions about your life's direction. Judgement teaches that you're being given a chance to rise to a new level of consciousness and understanding. This is a period of self-evaluation, reflection, and making peace with the past. The Judgement card encourages you to forgive yourself and others, release guilt and shame, and embrace a fresh start. It represents resurrection, renewal, and the opportunity to begin again with greater wisdom. Judgement often appears when you're experiencing a spiritual awakening, hearing your soul's calling, or being asked to step into your higher purpose. This card reminds you that you're being judged not by others but by your own higher self, and that it's time to align your life with your deepest values and truths.`, reverse: `When reversed, Judgement indicates self-doubt, harsh self-criticism, or inability to forgive yourself or others. You may be ignoring your inner calling, avoiding necessary self-evaluation, or refusing to take responsibility for your actions. This card can suggest that you're being too hard on yourself, dwelling on past mistakes, or unable to move forward due to guilt or shame. You might be resisting change, ignoring opportunities for renewal, or refusing to answer your soul's calling. The reversed Judgement can also indicate fear of judgment from others or inability to make important decisions. It's time to practice self-compassion, forgive yourself and others, and embrace the opportunity for rebirth and renewal.` },
    { number: 21, name: 'The World', icon: '🌍', image: 'asset/tarot/21_World.jpg', meaning: `The World represents completion, fulfillment, and the achievement of wholeness. This card signifies the successful conclusion of a major cycle and the integration of all you've learned along the way. The World teaches that you've come full circle, accomplished your goals, and are ready to begin a new journey from a place of greater wisdom and experience. This is a time of celebration, recognition, and feeling a sense of unity with all of life. The World card encourages you to acknowledge your achievements, honor your journey, and prepare for new adventures. It represents cosmic consciousness, global awareness, and understanding your place in the larger scheme of things. The World often appears when you're experiencing success, completion of long-term projects, or reaching important milestones. This card reminds you that endings are also beginnings, and that by completing one cycle, you're preparing for the next level of your evolution.`, reverse: `When reversed, The World indicates incomplete cycles, lack of closure, or difficulty finishing what you've started. You may be experiencing delays in completion, taking shortcuts, or avoiding the final steps necessary for success. This card can suggest that you're seeking external validation rather than finding fulfillment within, or that you're not fully integrating the lessons of your journey. You might be feeling stuck, unable to move forward, or experiencing obstacles that prevent completion. The reversed World can also indicate that you're ready for completion but external circumstances are causing delays. It's time to tie up loose ends, complete unfinished business, and prepare yourself for the next chapter of your journey.` }
];

// Merge the two arrays
tarotDeck.push(...tarotDeck2);

document.addEventListener('DOMContentLoaded', () => {
    const btnShuffle = document.getElementById('btn-shuffle');
    const board = document.getElementById('tarot-board');
    const selector = document.getElementById('spread-selector');
    const deckSelector = document.getElementById('deck-selector');

    // Modal Elements
    const modal = document.getElementById('reading-modal');
    const btnCloseModal = document.getElementById('btn-close-modal');
    const modalTitle = document.getElementById('modal-title');
    const modalText = document.getElementById('modal-text');

    let currentSpread = [];
    const spreadLabels6Card = ['Past', 'Present', 'Future', 'Hidden Influences', 'Advice / Action', 'Potential Outcome'];
    const spreadLabels3Card = ['Past', 'Present', 'Future'];
    const spreadLabels1Card = ['Guidance'];

    // Initialize Empty Board
    dealCards(6);

    btnShuffle.addEventListener('click', () => {
        const spreadValue = selector.value;
        const numCards = spreadValue === 'yesno' ? 1 : parseInt(spreadValue);
        const deckType = deckSelector.value;
        dealCards(numCards, deckType, spreadValue);
    });

    btnCloseModal.addEventListener('click', () => {
        modal.classList.remove('show');
    });

    function dealCards(numCards, deckType = 'major', spreadValue = '1') {
        board.innerHTML = '';

        // Select deck based on user choice
        let activeDeck = deckType === 'full' && typeof minorArcana !== 'undefined' ? [...tarotDeck, ...minorArcana] : tarotDeck;
        currentSpread = getUniqueCards(numCards, activeDeck);

        let labels = spreadLabels1Card;
        if (spreadValue === 'yesno') labels = ['Yes / No Outcome'];
        if (numCards === 3 && spreadValue !== 'yesno') labels = spreadLabels3Card;
        if (numCards === 6 && spreadValue !== 'yesno') labels = spreadLabels6Card;

        currentSpread.forEach((cardObj, index) => {
            const cardUI = document.createElement('div');
            cardUI.className = 'tarot-card-container';

            // Randomly reverse some cards (common in tarot readings)
            const isReversed = Math.random() > 0.7;

            let frontContent = '';
            if (cardObj.image) {
                frontContent = `
                    <div class='card-image-placeholder'>
                        <img src="${cardObj.image}" alt="${cardObj.name}" style="${isReversed ? 'transform: rotate(180deg);' : ''}" onerror="this.parentElement.innerHTML='<div class=\\'card-front-content\\' style=\\'${isReversed ? 'transform: rotate(180deg);' : ''}\\'><div class=\\'card-number\\'>${cardObj.number === 0 ? '0' : romanize(cardObj.number)}</div><div class=\\'card-image-placeholder\\' style=\\'background: linear-gradient(135deg, #f3f4f6, #e5e7eb); width: 120px; height: 180px; border-radius: 8px;\\'>${cardObj.icon}</div><div class=\\'card-title\\'>${cardObj.name}</div></div>';">
                    </div>
                    ${isReversed ? '<div style="position: absolute; bottom: 0; left: 0; right: 0; background: rgba(0,0,0,0.8); padding: 8px; font-size: 0.9rem; letter-spacing: 2px; color: #ef4444; font-weight: bold; z-index: 10;">REVERSED</div>' : ''}
                `;
            } else {
                frontContent = `
                    <div class='card-front-content' style="${isReversed ? 'transform: rotate(180deg);' : ''}">
                        <div class='card-number'>${cardObj.number === 0 ? '0' : romanize(cardObj.number)}</div>
                        <div class='card-image-placeholder' style="background: linear-gradient(135deg, #f3f4f6, #e5e7eb); width: 120px; height: 180px; align-self: center; border-radius: 8px;">
                            ${cardObj.icon}
                        </div>
                        <div class='card-title'>${cardObj.name}</div>
                    </div>
                    ${isReversed ? '<div style="position: absolute; bottom: 0; left: 0; right: 0; background: rgba(0,0,0,0.8); padding: 8px; font-size: 0.9rem; letter-spacing: 2px; color: #ef4444; font-weight: bold; z-index: 10;">REVERSED</div>' : ''}
                `;
            }

            cardUI.innerHTML = `
                <div class='card-label'>${labels[index]}</div>
                <div class='tarot-card'>
                    <div class='card-face card-back'></div>
                    <div class='card-face card-front'>
                        ${frontContent}
                    </div>
                </div>
            `;

            board.appendChild(cardUI);

            // Add click-to-flip functionality
            let hasFlipped = false;
            cardUI.addEventListener('click', () => {
                const innerCard = cardUI.querySelector('.tarot-card');
                const label = cardUI.querySelector('.card-label');

                if (!hasFlipped) {
                    // Flip the card
                    innerCard.classList.add('flipped');
                    label.style.opacity = '1';
                    hasFlipped = true;
                } else {
                    // Open Reading Modal
                    openReading(cardObj, isReversed, labels[index]);
                }
            });
        });
    }

    function getPositionMeaning(position) {
        const positions = {
            'Past': 'Events or energies from your past that have led to the current situation.',
            'Present': 'Your current state of mind, the core of the problem, or the immediate circumstances.',
            'Future': 'The likely outcome or direction things are heading if current energies remain unchanged.',
            'Hidden Influences': 'Underlying factors, subconscious thoughts, or hidden forces at play you might not be aware of.',
            'Advice / Action': 'The recommended approach, action to take, or perspective to adopt moving forward.',
            'Potential Outcome': 'The ultimate resolution or long-term result if you follow the advice given.',
            'Guidance': 'Daily insight, cosmic advice, or the overall energy surrounding you right now.',
            'Yes / No Outcome': 'A direct answer to your question. Upright cards generally lean towards "Yes" or positive momentum, while reversed cards lean towards "No" or signify internal blockages and delays.'
        };
        return positions[position] || 'The focus of this specific placement.';
    }

    function openReading(card, isReversed, position) {
        modalTitle.innerText = `${card.name} ${isReversed ? '(Reversed)' : ''}`;

        let interpretation = `
            <div style="background: rgba(139, 92, 246, 0.1); border-left: 3px solid var(--accent-purple); padding: 15px; margin-bottom: 20px; border-radius: 4px;">
                <p style="margin: 0; color: var(--accent-glow);"><strong>Position Focus: ${position}</strong></p>
                <p style="margin: 5px 0 0 0; font-size: 0.9rem; color: var(--text-light);">${getPositionMeaning(position)}</p>
            </div>
            <div style="text-align: center; margin: 20px 0;">
                ${card.image ? `<img src="${card.image}" alt="${card.name}" style="max-height: 400px; border-radius: 12px; box-shadow: 0 10px 30px rgba(0,0,0,0.5); ${isReversed ? 'transform: rotate(180deg);' : ''}">` : `<p style="font-size: 4rem; margin: 0;">${card.icon}</p>`}
            </div>
        `;

        if (position === 'Yes / No Outcome') {
            // Determine simple Yes/No logic.
            // Complex cards (Tower, Death, Devil, Swords 3,9,10, pentacles 5, cups 5) are generally 'No' upright and may be 'Yes' reversed or still 'No'
            let isInherentlyNegative = ['The Tower', 'Death', 'The Devil', 'Three of Swords', 'Five of Swords', 'Nine of Swords', 'Ten of Swords', 'Five of Cups', 'Five of Pentacles'].includes(card.name);

            let answer = '';
            let color = '';
            if (isReversed) {
                answer = isInherentlyNegative ? 'MAYBE / YES (Relief from negative forces)' : 'NO (Or Not Right Now)';
                color = isInherentlyNegative ? '#fbbf24' : '#ef4444'; // Yellow or Red
            } else {
                answer = isInherentlyNegative ? 'NO (Challenges Ahead)' : 'YES (Positive Momentum)';
                color = isInherentlyNegative ? '#ef4444' : '#10b981'; // Red or Green
            }

            interpretation += `
                <div style="background: rgba(0,0,0,0.3); border: 2px solid ${color}; padding: 20px; margin-bottom: 20px; border-radius: 12px; text-align: center;">
                    <h3 style="margin: 0; font-size: 2.5rem; color: ${color}; text-transform: uppercase; letter-spacing: 2px;">${answer}</h3>
                    <p style="margin: 10px 0 0 0; font-size: 0.9rem; color: var(--text-muted);">Based on card orientation and inherent archetype energy.</p>
                </div>
            `;
        }

        if (isReversed) {
            interpretation += `
                <p><strong>Core Energy:</strong> When drawn in reverse, the energy of this card turns inward. It suggests internal blockages, delays, or subjective internal experiences.</p>
                <p style="margin-top: 15px;"><strong>Card Meaning & Themes:</strong> ${card.reverse}</p>
                <p style="margin-top: 15px; padding: 10px; border: 1px dashed rgba(239, 68, 68, 0.4); border-radius: 8px;">
                    <strong>Application:</strong> In the context of the <em>${position}</em>, this reversed card asks you to reflect on these internal blocks or hidden resistances.
                </p>
            `;
        } else {
            interpretation += `
                <p><strong>Core Energy:</strong> Upright, this card expresses its energy outward into your life, external circumstances, and conscious awareness.</p>
                <p style="margin-top: 15px;"><strong>Card Meaning & Themes:</strong> ${card.meaning}</p>
                <p style="margin-top: 15px; padding: 10px; border: 1px dashed rgba(251, 191, 36, 0.4); border-radius: 8px;">
                    <strong>Application:</strong> In the context of the <em>${position}</em>, this card actively directs its themes toward resolving or illuminating this area.
                </p>
            `;
        }

        modalText.innerHTML = interpretation;
        modal.classList.add('show');
    }

    // Helper: Select random unique cards from the deck
    function getUniqueCards(count, deck = tarotDeck) {
        let deckCopy = [...deck];
        let selection = [];
        for (let i = 0; i < count; i++) {
            let randomIndex = Math.floor(Math.random() * deckCopy.length);
            selection.push(deckCopy.splice(randomIndex, 1)[0]);
        }
        return selection;
    }

    // Helper: Number to Roman Numeral generator
    function romanize(num) {
        if (isNaN(num)) return NaN;
        const digits = String(+num).split('');
        const key = ['', 'C', 'CC', 'CCC', 'CD', 'D', 'DC', 'DCC', 'DCCC', 'CM',
            '', 'X', 'XX', 'XXX', 'XL', 'L', 'LX', 'LXX', 'LXXX', 'XC',
            '', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX'];
        let roman = '', i = 3;
        while (i--) roman = (key[+digits.pop() + (i * 10)] || '') + roman;
        return Array(+digits.join('') + 1).join('M') + roman;
    }
});
